version: '3.1'

services:

  flask-app:
    build: ./
    image: bms-flask
    restart: always
    networks:
      - bmsnetwork
    ports:
      - 5000:5000

  mongo:
    image: mongo
    restart: always
    networks:
      - bmsnetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - bmsnetwork
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  bmsnetwork:
    driver: bridge
