version: 0.0
os: linux
files:
  - source: /
    destination: /vamsi
hooks:
  BeforeInstall:
    - location: /terminate/delete.sh
  AfterInstall:
    - location: /pipeline_scripts/installation.sh
      timeout: 3600
  ApplicationStart:
    - location: /pipeline_scripts/run.sh
      timeout: 3600
      
