version: 0.0
os: linux
files:
  - source: /
    destination: /vamsi
hooks:
  AfterInstall:
    - location: /src/installation.sh
      timeout: 3600
  ApplicationStart:
    - location: /src/run.sh
      timeout: 3600
      
